### ISSUE TITLE
Fix logo of tenant for mobile devices

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1029]
Logo of https://wald.senat-deutschland.de/ does not work on mobile devices - square logo would be better:

![B51F0A4A-D49A-41C2-8B39-AD0BB85B6815](https://user-images.githubusercontent.com/1532418/116348158-d5bdb700-a7ed-11eb-964e-60d9f4380f04.jpeg)

**Comment by sarveshpro** [comment]
I'll add an optional key in the tenant config for mobile logo.
For this particular tenant, I can either crop it and only use the globe or I can limit the width to make it smaller

**Comment by norbertschuler** [comment]
> I'll add an optional key in the tenant config for mobile logo.
> For this particular tenant, I can either crop it and only use the globe or I can limit the width to make it smaller

I'd vote for using the globe.

**Comment by sarveshpro** [comment]
Or they give us a new square icon for mobile and we will replace this

**Comment by sarveshpro** [comment]
https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1030
