### ISSUE TITLE
Make Gift Recipient Email optional

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-webapp#1048]
After pressing "Donate" on a project a Donation dialogue opens.
On the first page the user can press the button "This donation is a Gift to someone".
Afterwards it will ask the user to enter the email address of the gift recipient.

**Status Quo:**
The gift recipient email address field is mandatory.
And when the user succesfully finishies their donation a Gift invitation email is immediatly sent to the gift recipient email address.
This is bad. Since many users buy the gift a day or more before the occasion, spiling the surprise.

**Potential Solution 1:**
Make filling the gift recipient email address field optional.
And tell the users it is optional but an email will be sent, if they do fill it.

Portential Solution 2:
Keep the gift recipient email address mandatory,
but create a button the user can press, if they do actually want an email to be sent to the gift recipient.
If the button is left un-checked, it will not send an email to the gift recipient.
Default should be "no-email" (at least it seems that way in the support desk).

**Importancy:**
I had 5 support requests in the last week that were annoyed or confused by this.
This is a very common problem for users.

![gift_donation](https://user-images.githubusercontent.com/18365824/117433973-63a34b80-af2c-11eb-9745-1d8f670edc6a.PNG)

**Comment by mariahosfeld** [comment]
The recipient email is now optional, therefore closing this issue.
