### ISSUE TITLE
Legacy payment screen on mobile device might need improved design

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1067]
The screen to enter payment data coming from the Treecounter app is looking like there is something missing at the top empty area:

![IMG_9577](https://user-images.githubusercontent.com/1532418/118993166-949c6b00-b985-11eb-88b9-581e4545d65e.PNG)

**Comment by harshvitra** [comment]
> The screen to enter payment data coming from the Treecounter app is looking like there is something missing at the top empty area:

This will be not needed as we will use Planet Pay
