### ISSUE TITLE
Enable TIN Options for Spanish Tax Deductible Donation

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#1073]
If Tax deduction country = Spain,

We need to ask TIN from the user.

This can be done on the payments page.

Field Name "Personal Tax ID"
This field is required for both companies and for individuals.
This needs to be stored in the User Profile for repeat donations, and passed to the Tax Receipt System.

Note: Based on Info I have received, non Spanish Businesses can receive tax deductions as well. So we should not force address to Spain on the Billing Details page.

**Comment by mariahosfeld** [comment]
When a donor selects a receipt for Spain, they are prompted to provide the TIN, Country of the address can be switched to account for non Spanish businesses.
