### ISSUE TITLE
Mobile payment screen shows different currency

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1105]
**Describe the bug**
When we want to do a payment triggered from the Treecounter app switching from EUR to e.g. USD and opening the URL within the device browser, the amount is shown in the language derived from the browser (the settings the user already configured in the Planet Webapp or the default currency derived from the device language).

The donation afterwards is again done in the currency specified within the Treecounter app!

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Donate with Treecounter app
2. Switch currency
3. Open payment process in mobile browser

**Expected behavior**
Show the amount and currency chosen in the app and not the website.

**What actually happens**
The browser is showing the amount and currency with matches the browser settings.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2021-06-10 at 10 40 00](https://user-images.githubusercontent.com/1532418/121494013-a5665c80-c9d8-11eb-8378-4805475e3249.png)![Simulator Screen Shot - iPhone 11 - 2021-06-10 at 10 40 27](https://user-images.githubusercontent.com/1532418/121494024-a6978980-c9d8-11eb-81c8-8d0cf0227e6a.png)

**Smartphone (please complete the following information):**
- Device: iPhone 11 simulator
- OS: latest iOS
- Browser: Safari

**Comment by harshvitra** [comment]
Closing this as donations will happen with Donate with planet in future
