### ISSUE TITLE
TPOs: Editing Planting Site Polygons does Not Save Changes

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-webapp#1118]
_After a TPO changes a planting site's polygons it does not save those changes._

**Steps that lead to Bug:**
1. A TPO creates a project.
2. They add a planting site to the project.
3. They draw the polygon for that planting site.
4. They save that polygon.
5. Later they want to change the polygon.
6. They do this by dragging and dropping the polygon coordinates.
7. They save their changes.
8. The changes do not get saved, the polygon switches back to how it was drawn in 3.

**Production WebApp.**

**Comment by delightedMatt** [comment]
@sarveshpro Can you take a look at this?

**Comment by mariahosfeld** [comment]
Checked this out, the editing via drag and drop is working.
