### ISSUE TITLE
Site selector appars atop project description scroll

### ISSUE THREAD

**Issue by felixfinkbeiner** [Plant-for-the-Planet-org/planet-webapp#1146]
**Describe the bug**
Site selector should disappear behind scroll. See screenshot
![Screenshot_20210711-180355](https://user-images.githubusercontent.com/29404196/125212402-72e8a180-e2ad-11eb-91e0-77f19dc284a0.jpeg)

**To Reproduce**
1. Go to a project
2. Click on site selector
3. Scroll through the project description
4. The site selector should appear on top of the scroll

**Comment by norbertschuler** [comment]
This should be fixed together with https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1133.
