### ISSUE TITLE
Adress not questioned at signup for other types as TPO

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1234]
**Describe the bug**
The address is only requested for TPOs. Is this wanted or a bug?

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Signup
2. See error

**Screenshots**
<img width="461" alt="Bildschirmfoto 2021-09-04 um 17 30 08" src="https://user-images.githubusercontent.com/1532418/132099857-b2dc7721-8b44-4bbc-9315-324e2a6919b6.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome, Safari

**Comment by sagararyal** [comment]
This is not a bug. We do not need address of users who do not donate, or who do not add projects in the app.
