### ISSUE TITLE
Registered trees with Polygon are not shown on My Forest map

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1240]
My trees registration using a polygon is not displayed on the map on staging at https://planet-webapp-2eteloxyc-planetapp.vercel.app/t/norbert-schuler

<img width="1160" alt="Bildschirmfoto 2021-09-08 um 16 26 41" src="https://user-images.githubusercontent.com/1532418/132528143-850cd90a-d7a7-41aa-b04f-870ff74359e7.png">

**Comment by sarveshpro** [comment]
I registered 500 trees using my account on develop and it showed in my trees. But when I tried using plant-for-the-planet TPO account it registers successfully but the contribution is not returned by `GET /app/contributions` API. I am marking this as a backend issue and reporting it in channel

**Comment by norbertschuler** [comment]
@sarveshpro I get the contribution with the polygon in my API call, but it's not shown on the map:

<img width="1703" alt="Bildschirmfoto 2021-09-13 um 11 59 02" src="https://user-images.githubusercontent.com/1532418/133064397-1c9b2f53-3dc3-4ba7-b390-289161fc0964.png">

**Comment by sarveshpro** [comment]
Then I found another bug where if you register a large number of trees it is not shown in the API until `isVerified` is true. This is a backend change for `treesforjane` not sure if this will also be the case for other tenants.

**Comment by norbertschuler** [comment]
O.k., if you know where your tree was planted and zoom into the map far enough yourself, you can see the polygon:

<img width="732" alt="Bildschirmfoto 2021-09-13 um 14 24 00" src="https://user-images.githubusercontent.com/1532418/133082799-8d5f020c-57a9-4da9-973e-5cd49f4e5517.png">

**Comment by norbertschuler** [comment]
Being able to click on the item to navigate to the it would probably improve the issue.

**Comment by mariahosfeld** [comment]
Closing this, has been resolved
