### ISSUE TITLE
Translations missing in TreeMapper

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1244]
The red marked data is not translated in the UI:

<img width="384" alt="Bildschirmfoto 2021-09-09 um 16 53 26" src="https://user-images.githubusercontent.com/1532418/132709968-5e40a344-9d4b-4ccf-8e4d-5c4add3b39f0.png">

**Comment by sarveshpro** [comment]
`Unknown` is returned by the backend as `otherSpecies` , it is shown if scientific species is not found, I have added another check if `otherSpecies` is not found show 'Unknown' (translated) in #1249
