### ISSUE TITLE
Show Localized Tree Certificate 

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1254]
Append the current user locale, e.g. as /de to the certificate download link to allow the user to get a localized version of the PDF document. 

https://app-staging.plant-for-the-planet.org/certificate/Q231G5V3XQ9G -> https://app-staging.plant-for-the-planet.org/certificate/Q231G5V3XQ9G/de

**Comment by mariahosfeld** [comment]
Solved via the Backend.
