### ISSUE TITLE
Sample trees not visible on map in account section for Treemapper

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1304]
**Describe the bug**
Why can one not see any dots for sample trees (also on production)?

<img width="1178" alt="Bildschirmfoto 2021-10-14 um 11 41 56" src="https://user-images.githubusercontent.com/1532418/137293122-7a9b14ec-a376-4537-9761-7f80d8cf34c9.png">

**Is it on a Production or Development Build?**
production

**Comment by mariahosfeld** [comment]
Problem is not found on production.
