### ISSUE TITLE
Show verified and self-reported tree registration information on profile

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#1439]
This should be included as a part of contributions redesign.

Show source for all legacy tree registrations.

<img width="672" alt="Screen Shot 2022-03-10 at 1 42 41 PM" src="https://user-images.githubusercontent.com/5401575/157664281-8d42c755-60c9-442c-8e9d-c7087099108e.png">

<img width="413" alt="Screen Shot 2022-03-10 at 1 45 07 PM" src="https://user-images.githubusercontent.com/5401575/157664450-8122e59f-65e6-4b8f-a2fa-488e81f1e69b.png">

**Comment by mariahosfeld** [comment]
Closing this issue, as it will not work with the new design.
