### ISSUE TITLE
Payment History Download Gift Certificate 

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-webapp#1448]
When a user makes a donation with a gift invitation they receive 2 certificates: 
- 1 for the donor
- 1 Gift certificate for the gift recipient.
![gift-invitation](https://user-images.githubusercontent.com/18365824/158614581-ebc7fe78-5bee-4330-a31c-6917f8d600cb.PNG)

They receive these 2 certificates via email, which is great.

But please also make the Gift certificates downloadable in the user dashboard's payment history
=> Right below the Donation Certificate
![payment-history-gift-certificate](https://user-images.githubusercontent.com/18365824/158613239-71243d42-c0e4-47a1-a1c2-cc7b45d045ea.PNG)

**Comment by tejassonar** [comment]
Please check if accounting history returns the gift certificate

**Comment by delightedMatt** [comment]
It is not ==> an API change needs to be requested (I will request it and tell Sunil, when it is ready on Dev / Stg / Prd).
![payment-history](https://user-images.githubusercontent.com/18365824/159272986-0d6ee58f-47fe-491e-ac83-3c8ecd3e150f.png)

**Comment by mariahosfeld** [comment]
Fixed with the linked/mentioned pull request.
