### ISSUE TITLE
Certificate link for conservation projects result into error

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#1450]
**Describe the bug**
When you donate to a conservation project the donation is listed in the history in the account section of your profile. Using the link to download the certificate for the donation results into an error, e.g. `TCPDF ERROR: [Image] Unable to get the size of the image: /tmp/certoGHOge`.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Try to download the certificate for your donation on a conservation project
2. See error

**Expected behavior**
Either do not other download link of allow to create a proper certificate.

**Screenshots**
<img width="1116" alt="Bildschirmfoto 2022-03-19 um 16 28 21" src="https://user-images.githubusercontent.com/1532418/159127373-13cc416d-ff82-48c1-8bda-30fcd89134be.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome, Safari

**Comment by mariahosfeld** [comment]
Resolved, therefore closing this.
