### ISSUE TITLE
Widgets - Dashboard layout not seen after enabling public account 

### ISSUE THREAD

**Issue by mohitb35** [Plant-for-the-Planet-org/planet-webapp#1479]
**Describe the bug**
When a user's profile is private, they see an popup on /profile/widgets prompting them to switch to a public account. If they do so, by clicking on the CONTINUE button, they see the widget form. However only the form is visible, and the dashboard layout has disappeared.

**Is it on a Production or Development Build?**
Production  - https://www1.plant-for-the-planet.org/profile/widgets

**To Reproduce**
1. Go to Edit Profile, set profile to Private by toggling the Private Account switch to true and save the profile
2. Go to https://www1.plant-for-the-planet.org/profile/widgets by clicking on the Widgets link in the dashboard
3. On the modal/popup that appears, click CONTINUE.
4. The dashboard layout vanishes, including the header, header menu, and the side menu. Only the form component is visible

**Expected behavior**
After clicking CONTINUE within the Switch To A Public Account popup, user should see the widget form within the dashboard, with side menu, header menu, and header visible. It would look the same if the user came to /profile/widgets directly when their account was public.

**Screenshots**
_Switch to Public Account Popup_
![Screenshot 2022-05-09 at 11 38 22 AM](https://user-images.githubusercontent.com/44917347/167351324-6c77260e-e678-4c28-8785-d7e62b2744bf.png)

_After clicking CONTINUE_
![Screenshot 2022-05-09 at 11 38 29 AM](https://user-images.githubusercontent.com/44917347/167351311-2aecd18e-e4fc-4584-ab2d-b2b51f714994.png)

**Desktop (please complete the following information):**
- OS: MacOS 10.15.7 (Catalina)
- Browser: latest Chrome

**Comment by mariahosfeld** [comment]
Solved with PR #1526
