### ISSUE TITLE
Minor Code Refactors/Cleanup for Gift Funds

### ISSUE THREAD

**Issue by mohitb35** [Plant-for-the-Planet-org/planet-webapp#1600]
These are a few minor refactors that could be done to the code for Gift Fund.

- [x] https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1597#discussion_r1011746989 - Separate the render logic in [src/features/user/GiftFunds/Details.tsx](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1597/files/4f2fc5439c848c0751959893e8d7378047872175#diff-908982083223d15b152962dc54c401351477b6ab09c3bc54d5946bec6fa71bd7)
- [ ] https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1597#discussion_r1011744173 - Use a common component like `SingleColumnView` instead of an entirely new component `Details` in [src/features/user/GiftFunds/index.tsx](https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1597/files/4f2fc5439c848c0751959893e8d7378047872175#diff-3020e8d602785a7a4d5d76a542e9f306a4fd663a74186603a4ac1109b849e1d3)
- [ ] https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1597#discussion_r1011741966 - Used styled() to provide styling instead of modular scss

**Comment by mariahosfeld** [comment]
closed, as #1601 has been merged into develop.
