### ISSUE TITLE
Bug: Redeem code sends request twice for previous and new code resulting into `already_redeemed` error.

### ISSUE THREAD

**Issue by Shreyaschorge** [Plant-for-the-Planet-org/planet-webapp#1742]
Bug is related to the state management of previous Redeem code.

If user try to `Redeem Another Code` after redeeming a valid code, `Redeem Code` sends the request twice first for the previous code and second for new code. Thus resulting into `This code has already been redeemed` error

![image](https://user-images.githubusercontent.com/37466979/232947391-da8e7600-9067-49e0-979c-7cdcaaae9d6d.png)

- [ ] errorMessage isn't used anymore and should be removed. Also take care of places where setErrorMessage is being called with a value e.g. if the type is invalid.

**Comment by norbertschuler** [comment]
Is this the same or a different issue as https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1707?

**Comment by sunilsabatp** [comment]
fixed in this PR[https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/1746](url)
