### ISSUE TITLE
Multiple Donations requests are created when donation is initiated on map

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#180]
The app creates multiple requests for donations when donation process is initiated from the map and flyTo Projects is not complete.

The bug could be related to reloading stripe depending on the selections of the currency.

<img width="489" alt="Screen Shot 2020-09-10 at 9 05 48 PM" src="https://user-images.githubusercontent.com/5401575/92796688-afa7eb80-f3b1-11ea-851e-b25e89660fb5.png">

This still does not make multiple charge to the user's card as a paymentIntent can only be charged once. However the  donation process is slowed down by the requests.

**Comment by harshvitra** [comment]
@sagararyal it is now solved, please test once on develop
