### ISSUE TITLE
My Forest - Reset zoom level on selecting different contribution type

### ISSUE THREAD

**Issue by mohitb35** [Plant-for-the-Planet-org/planet-webapp#1982]
If I switch the type of contributions being seen in the map, the zoom level should probable be reset. For example, if I'm viewing `conservation` projects and click on the Conservation tile so that all contributions are seen. @sunilsabatp leave this if too complex for now

_Originally posted by @mohitb35 in https://github.com/Plant-for-the-Planet-org/planet-webapp/issues/1765#issuecomment-1711071109_

**Comment by mariahosfeld** [comment]
Closing issue, as it will no longer be an issue in the new implementation.
