### ISSUE TITLE
Title of page does not adjust after returning from Zoom 2 to Zoom 1

### ISSUE THREAD

**Issue by felixfinkbeiner** [Plant-for-the-Planet-org/planet-webapp#266]
<img width="1678" alt="Screenshot 2020-09-23 at 11 52 25" src="https://user-images.githubusercontent.com/29404196/94044143-0b20a300-fdce-11ea-934a-317ecc5db6a6.png">

When clicking on a project and then returning to Zoom 1, the title of the page remains the name of the project

**Desktop (please complete the following information):**
latest macOS w Chrome

**Comment by Plant-for-the-Planet** [comment]
@felixfinkbeiner this has been fixed in latest develop
https://dev.pp.eco/?p=agroforestry-to-assist-forest-restoration-in-the-dry-bolivian-andes
