### ISSUE TITLE
Country Name Translations

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#270]
Country Name should be localized [low priority]

<img width="499" alt="Screen Shot 2020-09-23 at 9 15 27 AM" src="https://user-images.githubusercontent.com/6512255/93979257-65454800-fd7d-11ea-9d27-88c2c77c45bf.png">

**Comment by norbertschuler** [comment]
There is only a normal input field for the country name yet in the edit profile form, so I could not integrate the translated country list there yet.
