### ISSUE TITLE
Translate language in html 

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#271]
The HTML language attribute at https://github.com/Plant-for-the-Planet/planet-webapp/blob/6e4864a2047d036de7b6bb7e55f98c795a877604/pages/_document.tsx#L15 is not localized - there is a discussion about doing this at https://github.com/isaachinman/next-i18next/issues/20 but that does not seem to work for static pages. Maybe someone know a good solution, also for changing this value when the user changes the languages.

**Comment by norbertschuler** [comment]
Not sure if Nextjs 10 solves this problem: 

> Since Next.js knows the language of the page visited by the user, it will automatically add the lang attribute to the `<html>` tag.


https://nextjs.org/blog/next-10
