### ISSUE TITLE
Disable Zoom when typing Address/ Tree Count for Donation on Mobile Browsers

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/planet-webapp#273]
Current view:
![IMG_6758D751E777-1](https://user-images.githubusercontent.com/6512255/94336445-ab9be080-ffe3-11ea-968a-9d949ab6e656.jpeg)

**Comment by sarveshpro** [comment]
@sagararyal already fixed?
