### ISSUE TITLE
Implement Direct Gift

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/planet-webapp#289]
url: /s/`username`

Direct gift increases the tree counter of the recipient through B Value (community value). 
Unlike other cases, In a direct gift, the donor knows the profile of the recipient. 

For the UI, we will need to convert - the username, to full name;

Once the validity of the username is confirmed, the username can be stored in local storage until removed by a user action.

Opening multiple links like
/support/username1 and then
/support/username2 would lead to store username2 in the list.

<img width="849" alt="Screen Shot 2020-10-05 at 9 23 21 AM" src="https://user-images.githubusercontent.com/6512255/95052676-a3345b80-06ef-11eb-8af6-52f3db6e9577.png">

--
The UI Below inherits the UI from multiple Gifts.

<img width="467" alt="Screen Shot 2020-10-05 at 10 02 06 AM" src="https://user-images.githubusercontent.com/6512255/95054238-ded02500-06f1-11eb-90ea-ed2ac0eaec04.png">

Clicking `Remove` will remove the recipient from the local storage; and instead load the normal gift form.

Disabling the Gift, will simply disable gift without affecting local storage. 

When support for multiple gifts are added, the user can add additional recipients.

**Comment by felixfinkbeiner** [comment]
Looks good! But lets use the URL /s/username
