### ISSUE TITLE
User Profile (Public/Private)

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/planet-webapp#291]
- [x]  1. If the user is logged in show settings on their user page : eg: /t/username

- [x] 2. [Public View] If the target is present, show the target, otherwise, planted trees will be centered. 
- [x] 2. / 3. [Logged In] Show target as 0, and allow user to set target.
- [x] 2. / 3. [Logged In] If target not 0 allow user to edit target.

- [x] Truncate the user description at 420 - 450 words after punctuation. [similar concept is implemented on read More on Single Projects] Additional text appears in a popup component.

- [x] Align the Name of the User to Center when it takes more than 1 line.

- [x] 4. [Logged In] Show three buttons, please use font awesome svg icons.

- [x] 4. [Public View]  Use Support & Share buttons [Support button should not exist for TPOs]

- [ ] [Logged In]  Contributions section - Clicking on contribution - fly to the project on right, Hover contribution on left - popup project on right

<img width="441" alt="Screen Shot 2020-10-05 at 3 20 12 PM" src="https://user-images.githubusercontent.com/6512255/95084571-5caa2580-071e-11eb-8bdf-993f36bc117e.png">

<img width="1068" alt="Screen Shot 2020-10-05 at 3 08 13 PM" src="https://user-images.githubusercontent.com/6512255/95083366-b7428200-071c-11eb-849c-41e499caf16e.png">

<img width="851" alt="Screenshot 2020-10-05 at 7 26 09 PM" src="https://user-images.githubusercontent.com/25605193/95088488-a86dc680-0740-11eb-8399-7ffa54c0869b.png">

**Comment by sagararyal** [comment]
```
This serves as the endpoint for extended scope and single contribution
{
  "type": "Feature",
  "properties": {
    "id": "con_uy8do71slA9d" //public
    "status": "pending|completed|cancelled", //public for (completed) private if pending/cancelled
    "creationDate": "10/10/2020", //registrationDate or donationDate
    "plantDate": "10/12/2020", //public -- either from registration or from treemapper
    "country": "NP",
    "mode": "registration|gift|donation", //private
    "treecount": 10, // public (sum of trees in this Contribution)
    "contributionImages": [],
    "sources":"html text", //for registrations  
    "treeSpecies" [   //applies for things registered with treemapper -- can be extended in v2.1
      [
        "speciesName": "apple", 
        "id": "spec_12345",
        "count": 10
      ],
      [
        "speciesName": "apple", 
        "id": "spec_12345",
        "count": 10
      ],
    ],
    "project":[ //public
      "name": "Yucatan Reforestation",
      "slug": "yucatan-reforestation",
      "location": "Yucatán, Mexico",
      "category": "tree"
    ],
    "project_owner":[
      "name": "Plant-for-the-Planet",
      "slug": "plant-for-the-planet",
      "address":[
        "line1": "Am Bahnhof 1",
        "city": "Uffing Am Staffelsee"
        "zip": 82449,
        "country": "DE"
      ]
    ],
    "donation": [ //if is a donation & private
      "tax-country": "DE", //if tax eligible
      "DNR": "XY12BA",
      "lastName": "FINKB"
      "donationDate": "10/10/2020"
    ],
    "recepient|giver":[ // based on gift to/from [private] can have multiple recepient
    "name": "Felix Finkbeiner",
    "slug": "felix-finkbeiner", //optional
    "avatar": null //optional
    "treecount": 10
  ],
},
```
