### ISSUE TITLE
Stern Bottom Navbar width issue

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#296]
Below 330 px the navbar breaks

<img width="355" alt="Screenshot 2020-10-07 at 5 13 43 PM" src="https://user-images.githubusercontent.com/25605193/95350156-7e9dd680-08dd-11eb-994b-f4e035e17343.png">

**Comment by sagararyal** [comment]
We can put the Hamburger menu on these insanely small screens. 
Will share a design for the overlay.

**Comment by sagararyal** [comment]
@felixfinkbeiner let's think of how we solve this.

**Comment by felixfinkbeiner** [comment]
@sagararyal @harshvitra General Rule: for the mobile menu, we always use the logo our partners use for the favicons. In the case of Stern, that is just the star with the red background (without the word "stern") and for "La Corqueta" it is "LC".
