### ISSUE TITLE
Translate Stripe Donation Error Messages

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#299]
Create Translations for Donation Messages.
<img width="498" alt="Screen Shot 2020-10-08 at 4 13 05 PM" src="https://user-images.githubusercontent.com/5401575/95470583-3f28c600-0981-11eb-84b6-bc9bc65f5daf.png">

**Comment by norbertschuler** [comment]
I just tested this locally on the `feature/cleaning` branch with Stripe test card 4000002760003184 (where I declined 3Dsecure to make it fail) and got a translated error message which exactly fits to your above English error message:

<img width="401" alt="Bildschirmfoto 2020-10-08 um 17 51 20" src="https://user-images.githubusercontent.com/1532418/95482974-e37a2f00-09b8-11eb-9933-f48e4afdf46f.png">

**Comment by norbertschuler** [comment]
Error message and translation are both coming from stripe.com which probably decides which language to use by the users browser language - maybe we can influence it?

<img width="1678" alt="Bildschirmfoto 2020-10-08 um 19 04 29" src="https://user-images.githubusercontent.com/1532418/95490878-11fd0780-09c3-11eb-83e8-ff51ae46998e.png">
<img width="1680" alt="Bildschirmfoto 2020-10-08 um 19 03 47" src="https://user-images.githubusercontent.com/1532418/95490882-132e3480-09c3-11eb-9331-74005b8b0848.png">
<img width="1680" alt="Bildschirmfoto 2020-10-08 um 19 02 07" src="https://user-images.githubusercontent.com/1532418/95490883-13c6cb00-09c3-11eb-83da-f023c23e77f0.png">

**Comment by sagararyal** [comment]
Stripe APIs allow passing preferred language when creating the customer. Not sure if that would solve this.

**Comment by norbertschuler** [comment]
I tried to initialize Stripe with the given locale, but I am afraid it does not work for me (Chrome on MacOS). The error messages still got loaded in German even if I switch the locale to English, clear my browser cache and restart the payment process - here is what I tested (maybe I did it wrong or there is another way to switch Stripes language): https://github.com/Plant-for-the-Planet-org/planet-webapp/compare/feature/get_stripe_localized?expand=1

**Comment by harshvitra** [comment]
The error messages coming from backend are not visible to the user

**Comment by harshvitra** [comment]
Maybe we try the language codes like en_US instead of en

**Comment by sagararyal** [comment]
closing as payments are no longer in this repo.
