### ISSUE TITLE
Disallow donation of 0 trees

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#315]
The Continue button can be disabled when the donation amount is 0 or less. However this might be tricky with payment request button.

As an alternative if 0 trees are selected override the value with minimum tree amount.
    
<img width="993" alt="Screen Shot 2020-10-12 at 11 30 46 PM" src="https://user-images.githubusercontent.com/5401575/95792194-3e769380-0ce3-11eb-826c-75e11b2b88f9.png">

<img width="1168" alt="Screen Shot 2020-10-12 at 11 31 32 PM" src="https://user-images.githubusercontent.com/5401575/95792205-42a2b100-0ce3-11eb-9b6a-b676e44699ab.png">

<img width="576" alt="Screen Shot 2020-10-12 at 11 32 21 PM" src="https://user-images.githubusercontent.com/5401575/95792211-46363800-0ce3-11eb-96a8-8daa1294858d.png">

**Comment by captainamiedi** [comment]
What i did was to check if the value is 0, I set the tree count to 1. I don't know if this is fine as well.
