### ISSUE TITLE
Implement OG Image generator for Profile Pages

### ISSUE THREAD

**Issue by Plant-for-the-Planet** [Plant-for-the-Planet-org/planet-webapp#320]

**Comment by harshvitra** [comment]
**Description -** 

Profile component is made of 
1. Tree Counter 
2. trees planted
3. the target 
4. the User name and description. 

<img width="1280" alt="Screenshot 2020-10-30 at 1 54 41 PM" src="https://user-images.githubusercontent.com/25605193/97677020-979e3f80-1ab7-11eb-97c9-790c73299875.png">


What is OG image ? 
OG images are shown when we share a link on any social media platform. 
This can be added in <meta> tag

But we need dynamic OG image for each different user. 

You can use this library to achieve this - https://github.com/vercel/og-image

**Comment by harshvitra** [comment]
Additional resource if needed - https://www.npmjs.com/package/puppeteer-core

**Comment by sarveshpro** [comment]
For meta tags to work they should be present in the initial render document sent from the server. to check this, view 
`view-source:https://dev.pp.eco/t/sagar-aryal` this is what a crawler bot sees. the meta tags should be present in this code for SEO to work.

next.js tends to render react/javascript code serverside unless it depends on local storage or an API call happening on client-side. right now all our API calls happen client-side. The only reason why SEO works for the homepage is that the data it returns is already present in the tenant config files. To fix SEO on other pages with dynamic data we will have to make API calls using serverless functions or maybe swr(I don't know much about swr) this way calls are made serverside and entire page is rendered serverside.

Step 1:
Make the `/app/profiles/${slug}` API call serverside to get user data, get static map image with planted markers using Mapbox static map API(also serverside), use the URL which Mapbox returns as the og:image.

Step 2:
generate a new image with the static map as background, user's profile image on top-right and treecounter bar at the bottom, somehow store it temporarily and use the URL.

**Comment by delightedMatt** [comment]
More context: https://kaydee.net/blog/open-graph-image/

But OG images aren't only used for Facebook, but Slack, Twitter, etc, etc
https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254
