### ISSUE TITLE
Improve email validation during donation

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#327]
In this case sagar_.@aryal.me is not a valid email.

<img width="1052" alt="Screen Shot 2020-10-17 at 1 30 11 AM" src="https://user-images.githubusercontent.com/5401575/96322194-6a15b880-1018-11eb-9ff0-916c56b8ef9d.png">

:Address in mailbox given [ssagar_.@aryal.me] does not comply with RFC 2822, 3.6.2.

Regex for RFC 2822 is:
```[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?```

**Comment by norbertschuler** [comment]
This ain't not fixed as Sagar's example mail is not validated, is it? Also my Google mail address like norbert.schuler+test@gmail.com is also not validated!
