### ISSUE TITLE
Spanish UI text for current production website

### ISSUE THREAD

**Issue by jigth** [Plant-for-the-Planet-org/planet-webapp#350]
Hi there!

Today I was looking around some repos about environment and I landed to the page [plant-for-the-planet homepage (english version)](https://www.plant-for-the-planet.org/en/home), then I noticed that you support more languages such as spanish, portuguese and german.

### Description:

I navigated to the page [plant-for-the-planet homepage (spanish version)](https://www.plant-for-the-planet.org/es/inicio) and noticed some text in german rather than spanish, for example, the text "Bäume gepflanzt" instead of "Árboles plantados".

I know that this webapp is different than the one you have in the site [https://www.plant-for-the-planet.org](https://www.plant-for-the-planet.org) but it´s publicly available so I thought it would be a good idea to make those corrections because of the importance of a homepage to a website. I put them here because I didn´t find a more appropiate chanel to send you that information.

#### Attachment:

I did an **attachment** (within this issue) with proposed translations for that text info. I think you could apply them if you want and it'd be useful to improve the first impression of the website to spanish-speakers.

Here it is: [plantsForThePlanet_Home_ES.txt](https://github.com/Plant-for-the-Planet-org/planet-webapp/files/5431449/plantsForThePlanet_Home_ES.txt)

#### Format of attachment:

Each paragraph is a sugested correction and the following format was used for each one of them:
> Current text for webpage => Sugested text for webpage

**Comment by sagararyal** [comment]
Thank you @jigth 

@jmiridis Could you review the text file and update it in the current website?

**Comment by norbertschuler** [comment]
LGFM on https://pftp2014-devel.plant-for-the-planet.org/es/inicio 😄
