### ISSUE TITLE
Donate button on project page does not work

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#355]
**Describe the bug**
The donate buttons on the projects list entries on a profile page do not work.

**Is it on a Production or Development Build?**
develop and production

**To Reproduce**
1. Go to https://dev.pp.eco/t/plant-together
2. See error not being able click the donate button

**Expected behavior**
Button should work and start the donate process.

**What actually happens**
Button does not work.

**Screenshots**
![Bild von iOS](https://user-images.githubusercontent.com/1532418/97464933-ce524980-1941-11eb-91a5-1953f1ffe676.jpg)

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser latest Chrome

**Comment by norbertschuler** [comment]
Maybe this is the same issue as the last open issue in #153.

**Comment by CallmeHongmaybe** [comment]
#366 Please check my PR

**Comment by norbertschuler** [comment]
Too many PRs trying to fix this *lol* - I linked them all!

**Comment by norbertschuler** [comment]
This is will be solved in https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/341 - I closed all other PRs.
