### ISSUE TITLE
Enhance i18 support?

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#356]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
The current delayed initialization of i18n shows the translation resource labels first before the real translation resources are loaded and shown. I know we wanted to enhance the site loading performance by not blocking until the translation resources are shown, but maybe there is another solution?

**What are the use cases for this feature?**
Do not show ugly translation labels names.

1. For about a second showing this on https://beta.plant-for-the-planet.org/ or https://dev.pp.eco/
<img width="952" alt="Bildschirmfoto 2020-10-28 um 17 28 46" src="https://user-images.githubusercontent.com/1532418/97467594-a6181a00-1944-11eb-8929-df8c33949608.png">

2. Finally showing the real page (e.g. in German):
<img width="950" alt="Bildschirmfoto 2020-10-28 um 17 28 38" src="https://user-images.githubusercontent.com/1532418/97467616-aca69180-1944-11eb-8bb6-9b4ee1bef0e9.png">

**Comment by sarveshpro** [comment]
Heather is working on this issue.

**Comment by CallmeHongmaybe** [comment]
Should we close the issue ? Bc I don't see this problem happening anymore

**Comment by norbertschuler** [comment]
> Should we close the issue ? Bc I don't see this problem happening anymore

The issue will be closed automatically after the linked pull request got merged.
