### ISSUE TITLE
Menu items not translated viewing on mobile devices

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#367]
**Describe the bug**
If you switch to a mobile device view (e.g with Chrome) the translation resources at https://dev.pp.eco for the navigation items are missing (while showing if viewing normally):

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to https://dev.pp.eco on a mobile device (or simulator or switch your browser to emulate a mobile view)

**Expected behavior**
Show translated menu items.

**What actually happens**
Show resource label names without the prefix (could this indicate the error?)

**Screenshots**
<img width="363" alt="Bildschirmfoto 2020-10-31 um 09 59 31" src="https://user-images.githubusercontent.com/1532418/97775310-31d2b600-1b92-11eb-830f-f7bda2bf007a.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

**Smartphone (please complete the following information):**
- Device: iPhone X
- OS: latest iOS
- Browser: latet Chrome

**Comment by harshvitra** [comment]
Added fix in #341
