### ISSUE TITLE
Settings icon almost not visible

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#368]
**Describe the bug**
At a certain width of the browser the settings icon on the me page is almost not visible.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Go to https://auth0.pp.eco/t/norbert-schuler
2. See error

**Expected behavior**
Add a drop shadow to the icon to be visible also on bright backgrounds.

**Screenshots**
<img width="832" alt="Bildschirmfoto 2020-10-31 um 10 30 03" src="https://user-images.githubusercontent.com/1532418/97775857-9132c500-1b96-11eb-90fb-06f138384c20.png">

**Comment by norbertschuler** [comment]
The problem does not exists on https://dev.pp.eco/me due to a different background - which version if the final one?

**Comment by sagararyal** [comment]
@norbertschuler the version on auth0.pp.eco is the final, we can add a circular button with shadow for this.
