### ISSUE TITLE
Country - Currency Pair List is broken

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#379]
In the Options to switch Currency both in donations and for Language switcher,

Country Currency Pair has been replaced by Country Name, country code.

<img width="682" alt="Screen Shot 2020-11-02 at 6 53 11 PM" src="https://user-images.githubusercontent.com/5401575/97901765-e7416d00-1d3c-11eb-8689-941d05c8f1e6.png">

Correct implementation would be: `Germany - EUR` instead of `Germany - DE`

Would recommend a hotfix.

**Comment by norbertschuler** [comment]
Sorry, that's probably my fault having translated the country names.

**Comment by norbertschuler** [comment]
Fixed with 7057d00b96a9c5ab0a87387382d3ef4697540efd - not yet hot fixed.

**Comment by norbertschuler** [comment]
@sagararyal we can cherry-pick the commit into master if you want?

**Comment by norbertschuler** [comment]
@sagararyal I created a hot fixing PR so you are able to test, approve and release it.
