### ISSUE TITLE
Improvements Post merge of Login branch

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#383]
- [x] Add translations in all the files. 
- [x] Translate months
- [x] Translate the date pickers
- [x] Signup Validations
- [x] Email Verification
- [x] Add multiple choice picker for owner type
- [x] User should not be able to add 2 reports for the same year.

In Project Sites 

- [x] Design on Safari
- [x] Delete should be replaced by Clear all
- [x] Another option to delete single
- [x] There should be add polygon button instead of polygon button
- [x] Disable drawing by default

**Comment by norbertschuler** [comment]
- [ ] Got this error trying to save a polygon for the site of a project:

```
Unhandled Runtime Error
TypeError: Cannot read property 'type' of undefined

Source
src/features/user/ManageProjects/components/ProjectSites.tsx (184:37) @ eval

  182 | })
  183 | .map((site) => {
> 184 |   const bbox = turf.bbox(site.geometry);
      |                         ^
  185 |   const { longitude, latitude, zoom } = new WebMercatorViewport(
  186 |     viewport
  187 |   ).fitBounds(
```

**Comment by norbertschuler** [comment]
@harshvitra what's missing to close this?
