### ISSUE TITLE
Dragging the deforestation slider is moving the map behind it

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#398]
**Describe the bug**
If you touch and drag the slider of the deforestation when using the new "explore" feature, the whole map of the earth is also moving in the background.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to https://dev.pp.eco/
2. Click on 'Explore'
3. Activate the 'Deforestation' checkbox
4. Grab a starting and ending point of the slider and drag it.
5. See map moving.

**Expected behavior**
Only move the slider when using it.

**What actually happens**
The whole map is being moved.

**Screenshots**
Before dragging:

<img width="799" alt="Bildschirmfoto 2020-11-07 um 10 31 56" src="https://user-images.githubusercontent.com/1532418/98437758-8d172200-2117-11eb-80b4-19f20f6d87ba.png">

After dragging:

<img width="799" alt="Bildschirmfoto 2020-11-07 um 10 32 12" src="https://user-images.githubusercontent.com/1532418/98437757-8ab4c800-2117-11eb-9f8e-58588c5dc002.png">

**Desktop (please complete the following information):**
- OS: e.g. latest MacOS
- Browser: e.g. latest Chrome

**Comment by norbertschuler** [comment]
@sarveshpro is this fixed by #421?

**Comment by sarveshpro** [comment]
Yes @norbertschuler

**Comment by sarveshpro** [comment]
fixed in #421
