### ISSUE TITLE
Redeem URLs

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#405]
Create pages for Redeem URLs

User's will use link pp.eco/CODE -
Fetch data from API using this code and
redirect them to 
URL - tenantUrl/redeem/CODE

Different designs for 
- Planted trees
- Gifted trees
- Organisation gifts

Different for logged in users

**Comment by harshvitra** [comment]
Designs

![pp eco-XYZ-1527-ABCD – 1 Tree Donor (Multiple Trees) – 1](https://user-images.githubusercontent.com/25605193/98530271-b1ecd000-22a4-11eb-9af4-800489d3d31c.png)

![pp eco-XYZ-1527-ABCD – 1 Tree Donor (Multiple Trees)](https://user-images.githubusercontent.com/25605193/98530286-b74a1a80-22a4-11eb-8c47-8dc71063df51.png)

![pp eco-XYZ-1527-ABCD](https://user-images.githubusercontent.com/25605193/98530289-b7e2b100-22a4-11eb-9617-4caa16b78b1a.png)

![t eco-XYZ-1527-ABCD – 1](https://user-images.githubusercontent.com/25605193/98530292-b87b4780-22a4-11eb-9850-38a71bdde5f3.png)

![t eco-XYZ-1527-ABCD – Corporate](https://user-images.githubusercontent.com/25605193/98530295-b913de00-22a4-11eb-8929-e9a5b0b7b28f.png)

**Comment by mariahosfeld** [comment]
Will be handled via #437 and #1568.
