### ISSUE TITLE
Improve Donations for Logged in Users

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#434]
Save contact details of the user who is logged in and show on the first page. 

Show the payment method on the first page. 

Enable direct payments from first page. 

Enable editing contact details

Enable editing payment method

<img width="237" alt="Screenshot 2020-11-12 at 10 33 00 AM" src="https://user-images.githubusercontent.com/25605193/98898607-04f89a00-24d4-11eb-941a-26d0443d225c.png">

**Comment by harshvitra** [comment]
Can be achieved with payment options returning the payment methods (similar to treecash payment method)

**Comment by mariahosfeld** [comment]
Closing this, is handled in the donations repo.
