### ISSUE TITLE
Hide 0 target when Add target is present

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#473]
In personal profile only.
<img width="458" alt="Screen Shot 2020-11-20 at 10 59 56 AM" src="https://user-images.githubusercontent.com/5401575/99787104-9a70db00-2b1f-11eb-81fd-e44c2c30a42e.png">

**Comment by captainamiedi** [comment]
These issue has been fixed on https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/420
