### ISSUE TITLE
Disable Cookie Note once user logs in

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#499]
If a user has logged in, disable this note.

![Screen Shot 2020-11-27 at 9 42 47 AM](https://user-images.githubusercontent.com/5401575/100428986-fb0a9580-3094-11eb-8a29-00fe8d87ac6d.png)

**Comment by norbertschuler** [comment]
@sarveshpro can you rewrite your already closed (and note merged!) PR as it was based on the old react auth0 module. I think Sagar wanted to create a new PR, but always closed it. I maybe make more sense to write the patch completely new :-)

**Comment by norbertschuler** [comment]
Done with #558
