### ISSUE TITLE
Remove all the console logs in the app

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#505]
**Describe the bug**
Remove all the console logs in the app. 
Either coded Or due to errors

**Is it on a Production or Development Build?**
develop 

**To Reproduce**
1. Go to different pages on the site
2. Click on inspect
3. See error

**Expected behavior**
A clear console log

**What actually happens**
Log with different errors or warnings.

**Screenshots**

**Comment by norbertschuler** [comment]
console.log is at least already removed within the deployment process.
