### ISSUE TITLE
Design a abstract error handling system for the app

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet-org/planet-webapp#511]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
A notification similar to cookie policy note should appear on the bottom right of the screen. Errors should be classified as - 

Error in UI -
Request Timed Out - Check your Internet connection
500 Error from Backend/app crash - Something went wrong
404 from API - Resource not found
Authentication Needed - You are not authorized

Maybe this article can help - https://itnext.io/centralizing-api-error-handling-in-react-apps-810b2be1d39d#9de2
https://itnext.io/centralizing-api-error-handling-in-react-apps-810b2be1d39d#fc03

Error in route - 
Page not found - redirect user to 404 page

Wrap all error-prone code in try-catch and make sure all API calls have promise rejection handled.

**What are the use cases for this feature?**

1. simplify error handling across the app
2. avoid logging errors in the console
3. let the user know what went wrong

**Comment by harshvitra** [comment]
After merging with donate with Plant-for-the-Planet we can come to this

**Comment by mariahosfeld** [comment]
Closing this, as system has been implemented.
