### ISSUE TITLE
Should config be stored as separate values in Storage?

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet-org/planet-webapp#515]
values returned by the config API - client IP, user country and currency. if stored separately can be fetched directly from local storage using getItem(), avoiding the need of a dedicated get function.

**Comment by norbertschuler** [comment]
I am pretty sure, that the duplicate way to store config values in the localStorage (once complete as `config` and also separately for `countryCode`, `currencyCode`) and now the first occurrence of loading country from `config` at https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/5a5e97c67b0ea5bff3394f8d8fc9e5a2d52c1240/src/features/user/UserProfile/components/RegisterTrees.tsx#L120 while usually loading it from `countryCode` directly, will surely raise bugs quite soon. We should only use one unique storage!
