### ISSUE TITLE
Replace country codes in country selector with currency code

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#530]
Please check Edit Profile, Signup, Donate and Project forms.
![Screen Shot 2020-12-02 at 10 56 49 AM](https://user-images.githubusercontent.com/5401575/100857611-2cb49f80-348d-11eb-9c68-5214f767f110.png)

**Comment by norbertschuler** [comment]
Why should we? A user in Germany is not bound to pay in EUR, is he? He might also want to pay in USD?

**Comment by sagararyal** [comment]
@norbertschuler As long as the German User wants a tax deduction receipt, he should pay in EUR.

This also saves 1-2% in foreign txn fees as fees in Germany are often lower than US.
This also simplifies the tax deduction setup.

**Comment by norbertschuler** [comment]
> But I agree currency in the dropdown might not be best idea designwise.

Then let's not do this :-)
