### ISSUE TITLE
Any route with query parameter "error" gives invalid state

### ISSUE THREAD

**Issue by sarveshpro** [Plant-for-the-Planet-org/planet-webapp#542]
This results in 404 redirects get stuck in invalid state loop and then redirected to home page

affected URL - 
https://planet-webapp-r1cctcyrw.vercel.app/404?error=Not%20Found
https://planet-webapp-r1cctcyrw.vercel.app/404?error=<basically anything here>

This seems to be causing it -
https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/5a5e97c67b0ea5bff3394f8d8fc9e5a2d52c1240/pages/_app.tsx#L39

**Comment by norbertschuler** [comment]
Got that from here: https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#3-protecting-a-route-in-a-nextjs-app-in-spa-mode - maybe we can just delete it again.

**Comment by sagararyal** [comment]
Should be fixed by #596

**Comment by norbertschuler** [comment]
Do not happen anymore with https://www.trilliontreecampaign.org/adfgdsffgfg
