### ISSUE TITLE
Footer - UNEP Logo - Logo Size

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-webapp#580]
The UNEP Logo scales with the Window Size xD

Which gets pretty big.
E.g.: https://www.trilliontreecampaign.org/all
e.g.: https://www.trilliontreecampaign.org/t/matthias-betz

![footer_size](https://user-images.githubusercontent.com/18365824/101195752-2aef0580-3660-11eb-8fea-57d404a68871.PNG)

**Comment by delightedMatt** [comment]
Firefox, Version 83.0 (64-Bit)

**Comment by sagararyal** [comment]
can replicate this on macOS Firefox as well

![Screen Shot 2020-12-06 at 10 21 03 AM](https://user-images.githubusercontent.com/5401575/101276407-c097ab80-37ac-11eb-9c5f-73d1c4e0bac3.png)
