### ISSUE TITLE
Download donation congratulations Image crashes mobile chrome browser 

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#583]
**Describe the bug**

Downloading the donation congratulations image crashes the mobile chrome browser on iOS. 

**Is it on a Production or Development Build?**
production 

**To Reproduce**
1. Donate 
2. Click to download image in browser 
3. Browser is frozen, crashes our some seconds 

**Expected behavior**
Do not crash. 

**What actually happens**
Download image as mobile Safari can do it. 

**Screenshots**
![50F78EC7-8165-49FF-8C5E-05534E22F534](https://user-images.githubusercontent.com/1532418/101211811-0acb4080-3678-11eb-846f-ff3fd1a83442.jpeg)

**Smartphone (please complete the following information):**
- Device: iPhone X
- OS: iOS 14.2
- Browser: latest Chrome 

**Additional context**
Maybe a rare usecase.

**Comment by norbertschuler** [comment]
Can someone test this on Android?

**Comment by harshvitra** [comment]
> Can someone test this on Android?

Works on android

**Comment by captainamiedi** [comment]
I try debuging these but i couldn't produce the error. i use iPhone 12 and chrome as well on browser stack
![thank u page](https://user-images.githubusercontent.com/48450805/101361504-57dd2b80-389f-11eb-95b8-888d99a68a44.JPG)

**Comment by norbertschuler** [comment]
> I try debuging these but i couldn't produce the error. i use iPhone 12 and chrome as well on browser stack

Well, then it's a even more rare edge case (iOS using Chrome using iPhone X). If nobody but me can reproduce it, then maybe we don't put any more effort in it.

**Comment by harshvitra** [comment]
Closing this until someone else reproduces the same error
