### ISSUE TITLE
Opening installed app by deep link while signup/login

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#584]
**Describe the bug**
We have an issue using the website on mobile devices (at least iPhones) when trying to login with Google, Apple etc.: If you try to sign up or login and have the native apps installed and the browser switches back from accounts.google.com or accounts.plant-for-the-planet.org to https://www.trilliontreecampaign.org/ the native app is launched (because of the deep links defined). If the users visits the website again, he first gets a session error from Auth0, but later on, he is logged in. 

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Sign up or login with Google account
2. See error switching to an installed native app

**Expected behavior**
Do not switch to native apps in login or signup process.

**Screenshots**

**Smartphone (please complete the following information):**
- Device: iPhone X
- OS: iOS 14.2
- Browser: latest Chrome

**Comment by norbertschuler** [comment]
I assume the deep link `login*` at https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/4c2fb4584951d63b71879d6f80ed31e9db43cf7d/public/.well-known/apple-app-site-association#L7-L14 is responsible for opening the app as it's also triggered by Auth0:

<img width="978" alt="Bildschirmfoto 2020-12-04 um 23 54 59" src="https://user-images.githubusercontent.com/1532418/101223430-a1baeb80-36be-11eb-8632-e589e9783c7a.png">

We could remove that from the list of deep links for the iOS app by modifying the above file while for Android we would have to change and release the Android app as the deep links are defined within the app's Manifest file.

**Comment by harshvitra** [comment]
Should this issue be shifted to Tree counter app ? 
@norbertschuler @sagararyal

**Comment by norbertschuler** [comment]
Test deep links with
- Android `adb shell am start -a android.intent.action.VIEW -d https://www.trilliontreecampaign.org/login`
- iOS `xcrun simctl openurl booted https://www.trilliontreecampaign.org/login`
