### ISSUE TITLE
Share to Twitter/Facebook not working in iOS Safari

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#593]
**Describe the bug**
Facebook and Twitter sharing does not work on iOS with the Safari browser (they just do nothing but highlighting the icon). On the mobile Chrome app Twitter works and Facebook is opening as a website where you have to login, not opening the native Facebook app.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Make a donation
2. Share to Twitter or Facebook
3. See error

**Expected behavior**
Open Facebook or Twitter apps (or websites) and share the message.

**Smartphone (please complete the following information):**
- Device: iPhone X
- OS: iOS 14.2
- Browser: latest Safari / latest Chrome

**Comment by harshvitra** [comment]
Instagram doesn't work on iOS latest and safari
