### ISSUE TITLE
Wait for i18n to be initialized, do not show placeholder

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#594]
**Describe the bug**
i18n is not completely initialized before rendering our components. Instead we rely on the components to be rendered again after i18n is ready. We should wait for the first render of a component with text resources until i18n is completely initialized and show a loading indicator instead. Currently the user sometimes sees the placeholder text for a resource.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Load a page (best without cache, so loading is slower)
2. See error

**Expected behavior**
Do not show i18n placeholder. Always wait until i18n is initialized before rendering any text resources.

**What actually happens**
Showing i18n placeholders.

**Screenshots**
<img width="193" alt="Bildschirmfoto 2020-12-05 um 15 14 37" src="https://user-images.githubusercontent.com/1532418/101245424-75937f00-373f-11eb-9d95-cadba01005d6.png">

**Comment by sagararyal** [comment]
Testing this with Browserstack on different browsers results only placeholders appearing on the screen. Need to find a fix soon.

**Comment by norbertschuler** [comment]
Ok, I could not yet reproduce the error showing only more placeholders. If we keep the current solution, we could add more usage of the `ready` state of i18n in our components like this to prevent showing placeholders:

<img width="440" alt="Bildschirmfoto 2020-12-06 um 14 10 12" src="https://user-images.githubusercontent.com/1532418/101280984-1137f480-37ff-11eb-942b-9d5edbdfeeea.png">

E.g. https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/01eab48e916a3c6ba606b111a74fad8c8fc17e78/src/features/common/Layout/Navbar/index.tsx#L191-L195
