### ISSUE TITLE
Optimize Nextjs code loading

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#602]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
Check if Nextjs can be optimized e.g. with https://nextjs.org/docs/advanced-features/dynamic-import to load less or unused code to improve loading and evaluate time for the JavaScript code.

**What are the use cases for this feature?**
Currently the site takes quiet long until all JavaScript code is loaded and evaluated. According to Chrome's Lighthouse test report this is using up the most time:

<img width="825" alt="Bildschirmfoto 2020-12-06 um 13 23 52" src="https://user-images.githubusercontent.com/1532418/101279944-979d0800-37f8-11eb-95b2-5b5288e23e17.png">

<img width="828" alt="Bildschirmfoto 2020-12-06 um 13 25 06" src="https://user-images.githubusercontent.com/1532418/101279965-c6b37980-37f8-11eb-80d6-afa06a449f68.png">

**Comment by norbertschuler** [comment]
Looking better testing again for https://www1.plant-for-the-planet.org/

<img width="815" alt="Bildschirmfoto 2020-12-15 um 13 28 46" src="https://user-images.githubusercontent.com/1532418/102215451-526d8a00-3f0c-11eb-9ca8-136a32aa87dc.png">
<img width="812" alt="Bildschirmfoto 2020-12-15 um 13 32 16" src="https://user-images.githubusercontent.com/1532418/102215466-55687a80-3f0c-11eb-8d77-44a4227fe9af.png">

**Comment by harshvitra** [comment]
New score is better
[lighthouse score.pdf](https://github.com/Plant-for-the-Planet-org/planet-webapp/files/6808874/lighthouse.score.pdf)

**Comment by norbertschuler** [comment]
Then I would close this.
