### ISSUE TITLE
Correct currency amount formatting

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#609]
This issue is about clarifying is the current usage for formatting amounts with a currency are correct or need a change:

1. On the main page and single project page the price and currency is displayed like chosen by the user:

<img width="853" alt="Bildschirmfoto 2020-12-07 um 16 47 54" src="https://user-images.githubusercontent.com/1532418/101373004-10768f80-38df-11eb-9a19-d775c58f3a6e.png">

2. On the TPO profile page the projects are always listed with the donation amount formatted in the projects currency (unlike on our main page or single project page) - right or wrong?

<img width="1045" alt="Bildschirmfoto 2020-12-07 um 16 46 07" src="https://user-images.githubusercontent.com/1532418/101372991-0ce30880-38df-11eb-8f2a-75f31b117fef.png">

3. On the single projects page financial project spendings are always displayed as € - right or wrong?

<img width="852" alt="Bildschirmfoto 2020-12-07 um 16 49 24" src="https://user-images.githubusercontent.com/1532418/101373005-11a7bc80-38df-11eb-83c9-d30ed0ec8ef7.png">

**Comment by harshvitra** [comment]
> 1. On the single projects page financial project spendings are always displayed as € - right or wrong?

This will always be like this. 

Correct me if I'm wrong @sagararyal

**Comment by sagararyal** [comment]
Financial reports will always be displayed in Euro for now.
We might convert that in future.

1 is correct

2 (not sure if API supports currency query in different one) Not priority.
