### ISSUE TITLE
Website is shown without styles and in English first

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#627]
The website is displayed without the right styles and with English resources before the styles got applied and the language is switched to the language the user has chosen:

<img width="344" alt="Bildschirmfoto 2020-12-09 um 23 13 02" src="https://user-images.githubusercontent.com/1532418/101695766-a78e4380-3aa7-11eb-8db3-cc7dcd38f10f.png"><img width="343" alt="Bildschirmfoto 2020-12-09 um 23 13 07" src="https://user-images.githubusercontent.com/1532418/101695769-a8bf7080-3aa7-11eb-91b7-f862afcad9f7.png">

As this is happening only when deployed as static sites, it's not easy to test with running `npm run dev`.

**Comment by mariahosfeld** [comment]
Closing this as it is more than 3 years old.
