### ISSUE TITLE
Adapt tree prices after currency change

### ISSUE THREAD

**Issue by jonas-hoebenreich** [Plant-for-the-Planet-org/planet-webapp#667]
**Adapt tree prices after currency change**
After you switched the currency the prices for the trees are still the same.

**Is it on a Production or Development Build?**
Production 

**To Reproduce**
1. Go to https://www.trilliontreecampaign.org/
2. Switch the currency
4. See wrong price labeling

**Expected behavior**
Show prices in the selected currency

**What actually happens**
prices do not change

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

**Desktop (please complete the following information):**
Browser Chrome & Firefox

**Additional context**
Maybe you can just reload the page after the user switched the currency?

**Comment by sagararyal** [comment]
![Screen Shot 2020-12-19 at 7 52 14 PM](https://user-images.githubusercontent.com/5401575/102697138-bad1a980-4233-11eb-8954-4fb01c29ae19.png)


![Screen Shot 2020-12-19 at 7 52 37 PM](https://user-images.githubusercontent.com/5401575/102697144-c9b85c00-4233-11eb-9835-9a09f5a8b563.png)


In this case after saving the currency, the project api needs to be refetched using the new currency.
