### ISSUE TITLE
Uploading bigger reports to project fails

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#691]
**Describe the bug**
I tried to upload a bigger report file (> 20MB) to my project. Within the upload process I got an error and the app is frozen in the upload process (not handling this error properly).

A file of the size 21.142.000 bytes failed to upload, two file of the size 19.201.698 bytes and 18.292.075 bytes successfully got uploaded.

**Is it on a Production or Development Build?**
develop

**To Reproduce**
1. Go to Manage Projects
2. Open a projects
3. Upload a bigger PDF as a project spending report

**Expected behavior**
Avoid or at least handle the error

**What actually happens**
App is frozen.

**Screenshots**
<img width="1667" alt="Bildschirmfoto 2020-12-21 um 11 15 18" src="https://user-images.githubusercontent.com/1532418/102766323-89321d00-43b0-11eb-82e1-ee78d02d8c42.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

**Comment by sagararyal** [comment]
We should mention max file size and validate the file size.
Maybe around 5-10 MB
