### ISSUE TITLE
Add brief explanation of the redemption / registration function

### ISSUE THREAD

**Issue by jonas-hoebenreich** [Plant-for-the-Planet-org/planet-webapp#755]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
Please add a short explanation of the redeem / registration function in the respective popup. At this time, the functions can be easily misunderstood or confusing.

**What are the use cases for this feature?**
Understand the function of the redeem / register buttons

**Examples of this feature or functionality.**
See screenshots

**Feature Checklist**

- [x] I have searched for existing issues and to the best of my knowledge this is not a duplicate
- [x] I have included at least one example image if it could be helpful (optional)
- [ ] The request requires change in APIs, Backend, etc (optional)
![grafik](https://user-images.githubusercontent.com/64426524/104924298-84f02400-599d-11eb-900e-0c610db15a08.png)
![grafik](https://user-images.githubusercontent.com/64426524/104924529-dac4cc00-599d-11eb-9193-112694e81abf.png)

**Comment by norbertschuler** [comment]
I like this as I think myself users might use the function wrongly and need some small description. Thus I implemented a PR for this.

**Comment by jonas-hoebenreich** [comment]
Thank you :)
Yes, there are always inquiries from users who get this wrong. And I assume that most of them do not reach out to us
