### ISSUE TITLE
Fix errors caused by unsupported currencies for donations

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#773]
**Describe the bug**
The API call for payment options, e.g. https://app.plant-for-the-planet.org/app/projects/proj_zoj2MAHlXzibgydQbif5CZBo/paymentOptions?country=AQ
 can reset the chosen currency in the donation popup to EUR, so the selected value of the currency chooser dialog gets changed and this dialog does not display any preselected country+currency anymore. If chosen such a unsupported currency twice, it keeps being displayed with the wrong amounts in EUR until the payment finally fails.

**Is it on a Production or Development Build?**
production

**To Reproduce**
1. Open donation popup for a project
<img width="422" alt="1" src="https://user-images.githubusercontent.com/1532418/105323871-448ee100-5bfd-11eb-9e73-96a9a8b91578.png">

2. Click on choosing another currency and choose currency of e.g. `Antarctica · AQD`
<img width="560" alt="2" src="https://user-images.githubusercontent.com/1532418/105323942-54a6c080-5bfd-11eb-9ab1-37776c42e0ce.png">

3. See that currency is reset from `AQD` to `EUR` again while tree cost amount is set to `0`.
<img width="421" alt="3" src="https://user-images.githubusercontent.com/1532418/105323982-625c4600-5bfd-11eb-8d6a-663985aaeac8.png">

4. Click on choosing another currency again and choose e.g. `Antarctica · AQD`
<img width="557" alt="4" src="https://user-images.githubusercontent.com/1532418/105324043-730cbc00-5bfd-11eb-9ee4-8123d96e3b62.png">

5. See that currency is now `AQD`
<img width="417" alt="5" src="https://user-images.githubusercontent.com/1532418/105324055-79029d00-5bfd-11eb-9119-d950ce54a052.png">

6. See error if trying to pay with chosen unsupported currency
<img width="419" alt="6" src="https://user-images.githubusercontent.com/1532418/105324069-7dc75100-5bfd-11eb-90c7-e39e66f61edf.png">

**Expected behavior**
Either remove all unsupported currencies from frontend (check against list of supported currencies from backend) or fix the reset of unsupported currencies in the donation dialog.

**Comment by sagararyal** [comment]
API response here has:
```{"treeCost":0.0,"currency":"EUR","effectiveCountry":"DE","requestedCountry":"AQ","gateways":{"stripe":{"isLive":true,"methods":["stripe_cc"],"account":"acct_1DYCMDD2OpW2f42N","recurrency":{"enabled":true,"intervals":["none","daily","weekly","monthly","quarterly","semiyearly","yearly"]},"authorization":{"stripePublishableKey":"pk_live_kgrdlpO8m5OZmfysUTSwbzrd","accountId":"acct_1DYCMDD2OpW2f42N"}}}}```

For effective country DE, and the currency EUR, treecost is 0; 

The calculation needs to be fixed. 

Even if frontend sends country that does not exist, it is job of the backend to return default currency, which it does here, but simply fails in calculation.

**Are the rates not being fetched from fixer?**

**Comment by norbertschuler** [comment]
- [ ] If the unsupported currency is in our list of currencies, e.g. for `XAF`of `Chad TD` to show the minimum donation amount (https://github.com/Plant-for-the-Planet-org/planet-webapp/blob/develop/src/utils/countryCurrency/countryExchangeForMinimumDonationAmount.json) the minimum donation amount is still shown in the EUR currency while the value got converted by the conversion rate which it should not do:

<img width="407" alt="Bildschirmfoto 2021-01-26 um 08 35 03" src="https://user-images.githubusercontent.com/1532418/105815493-8f39a000-5fe5-11eb-9e4c-8bd141e67e5a.png">
