### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#776]
Todos'

- [x] Assign unique id to divs to allow better tests and accessibility.

- [x] Convert buttons from div tags to `< button>` Eg: Donate buttons

- [ ] Change shade color form elements as they are invisible under certain circumstances.

- [x] Change button animations to match the design. Implement touchable actions.

**Comment by enroot-mumbai** [comment]
> * [ ]  Change shade color form elements as they are invisible under certain circumstances.

Can you explain this one ?

**Comment by harshvitra** [comment]
> * [ ]  Change shade color form elements as they are invisible under certain circumstances.
> *

Can you explain what is this ?
