### ISSUE TITLE
Use location data from config API call

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#779]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
The config API call now contains an approximated user location, e.g.
```
{
  "appVersions": {
    "ios": "1.3.5",
    "android": "1.3.5"
  },
  "clientIp": "xxx",
  "country": "DE",
  "currency": "EUR",
  "cdnMedia": {
    "images": "https://cdn.plant-for-the-planet.org/media/images",
    "cache": "https://cdn.plant-for-the-planet.org/media/cache",
    "pdfs": "https://cdn.plant-for-the-planet.org/media/uploads/pdfs"
  },
  "loc": {
    "latitude": "51.24800",
    "longitude": "7.12280",
    "city": "Wuppertal",
    "postalCode": "42117",
    "countryCode": "DE",
    "regionCode": "NW",
    "timezone": "Europe/Berlin"
  }
}
```
This can be used to show the users location on maps, form et al.

**What are the use cases for this feature?**
Center maps on user location, use user location as default value in forms.

**Comment by sarveshpro** [comment]
Yes, this is very much needed on register trees. I am working on this.
but I can't find it in config
![image](https://user-images.githubusercontent.com/27153515/109926830-6ba2fd00-7ce9-11eb-8eb0-853793f58410.png)

**Comment by sarveshpro** [comment]
location data is missing on app development 
https://app-development.plant-for-the-planet.org/public/v1.2/en/config

**Comment by sarveshpro** [comment]
I think it is because the config is added by a Cloudflare worker only on production

**Comment by sarveshpro** [comment]
@sagararyal can we create a similar worker for development and staging.

**Comment by norbertschuler** [comment]
@sarveshpro we probably would have to create two new workers for staging and develop as the CDN urls are included in the response or add some switches in there to return different CDN urls depending on the url the workers is called with. For a quick fix, you might just code our Planet-App the way it just optionally set the user location if the data is available and test with changing your local API endpoint to production?

**Comment by sarveshpro** [comment]
Sure

**Comment by sarveshpro** [comment]
This isn't tested, to test this on local with Production APIs requires login which is not possible because of Auth0

**Comment by norbertschuler** [comment]
@sarveshpro I added a Cloudflare worker for development (only supporting `en` and `de` and maybe returning wrong data for CDN urls).

**Comment by sagararyal** [comment]
As a part of this redesign, 
I would recommend avoiding locale and versions in config,

and simply using something like

config.plant-for-the-planet.org/locate

**Comment by sarveshpro** [comment]
This issue is worked on and merged creating a new PR for redesign

**Comment by sarveshpro** [comment]
#934
