### ISSUE TITLE
Location markers incorrectly drawn on big screen

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#789]
**Describe the bug**
On a big screen the markers for our TPO's on the map are initially wrongly located. Zooming fixes it.

**Is it on a Production or Development Build?**
production

**Screenshots**
![Bildschirmfoto 2021-01-31 um 13 54 08](https://user-images.githubusercontent.com/1532418/106467070-6f4e2480-649c-11eb-9df2-114523518455.png)

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome

**Comment by sarveshpro** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/8102

**Comment by sagararyal** [comment]
This has been fixed with latest refactor
