### ISSUE TITLE
Repeat selected item in country/currency list

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#790]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
Selected country should repeat again in the alphabetical list - even if it appears first or second.

<img width="1288" alt="Screen Shot 2021-01-27 at 1 52 20 AM" src="https://user-images.githubusercontent.com/1532418/106467361-d2d85200-649c-11eb-84ce-8a4619a98ef7.png">

**Comment by mariahosfeld** [comment]
Closing this in favor of #861
