### ISSUE TITLE
Implement further user contributions functionality

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#802]
The following issues should be checked and implemented for the user contributions:

- [ ] Are all kind of contributions (gifts et al) correctly displayed?
- [ ] Allow to edit and delete registered trees.
- [ ] Allow download of certificate (and receipt?) for a contribution.
- [ ] Use clustering to show contributions on the map (as in the widget)

**Comment by norbertschuler** [comment]
Not sure what issue https://github.com/Plant-for-the-Planet-org/planet-webapp/pull/695 is already implementing - @sarveshpro please adapt your pull request description.

**Comment by harshvitra** [comment]
@norbertschuler we are changing the entire implementation of this feature. So maybe we can create another enhancement issue and close this one.

**Comment by sagararyal** [comment]
Do not work on this yet!
