### ISSUE TITLE
Add an image cropper function for user images

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#878]
**Describe the feature you'd like to see included in Plant-for-the-Planet Web App.**
Allow the user to crop their images before uploading them into the backend.

Possible module to help:
- https://www.npmjs.com/package/react-easy-crop
- https://www.npmjs.com/package/react-image-crop
- https://www.npmjs.com/package/cropperjs

**What are the use cases for this feature?**
Avoid having uploaded too big images (compare #875) and to selected the right format and area of the image.

**Comment by mariahosfeld** [comment]
Will not be implemented on the frontend.
