### ISSUE TITLE
Integrate Auth0 in the app 

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-webapp#9]
Integrate Auth0 in the app - 

https://auth0.com/blog/ultimate-guide-nextjs-authentication-auth0/

Create a new Login-Register page and integrate Auth0 in there

**Comment by sagararyal** [comment]
https://next-auth.js.org supports Auth0 and should be a simple integration

If you need access to Auth0 credentials to test locally please reach me out on Slack.
