### ISSUE TITLE
Loading user contributions with 404 for private profile 

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-webapp#914]
**Describe the bug**
Viewing your own private profile the app tries to load the user contributions and gets a 404 response from the backend for e.g. for calling  https://app-development.plant-for-the-planet.org/app/profiles/prf_KL79s31SQaotgohmtXiETjcq/contributions (if my profile is set to private). The API call should be possible if you are viewing your own profile showing your own contributions.

**Is it on a Production or Development Build?**
production & develop

**To Reproduce**
1. Sign-In
2. Set your account to private (if not already done)
3. See error checking API requests in browser console

**Expected behavior**
The user should be allowed to view his own contributions. 

**What actually happens**
Trigger API calls and get a 404 response.

**Screenshots**
<img width="1660" alt="Bildschirmfoto 2021-03-18 um 09 48 25" src="https://user-images.githubusercontent.com/1532418/111598858-ef6fe580-87cf-11eb-9bf3-0c247d8cdca1.png">

**Desktop (please complete the following information):**
- OS: latest MacOS
- Browser: latest Chrome, Safari

**Comment by sagararyal** [comment]
In this case the client should simply pass the authorization headers for that API.

Contribution endpoint is available for private users as well
@sarveshpro

**Comment by norbertschuler** [comment]
> In this case the client should simply pass the authorization headers for that API.
> 
> Contribution endpoint is available for private users as well
> @sarveshpro

@sagararyal Thank you for the correction. I totally forget that I am logged in watching my own profile and of course have a valid interest to see my contributions. So this should be fixed the way to make the API call work and show the contributions of course ;-) I will rewrite the above issue now.

**Comment by norbertschuler** [comment]
> In this case the client should simply pass the authorization headers for that API.

Trying to load the contributions with the Authorization header set unfortunately still answers 404 for private profiles using the API call https://plant-for-the-planet.stoplight.io/docs/treecounter-platform/reference/App%202.0.v1.yaml/paths/~1profiles~1%7Bguid%7D~1contributions/get - @jmiridis can you please help us here?
