### ISSUE TITLE
Implement Image Lazy Loading for Project list

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-webapp#992]
https://web.dev/browser-level-image-lazy-loading/

<img width="487" alt="Screen Shot 2021-04-19 at 2 41 53 PM" src="https://user-images.githubusercontent.com/5401575/115237952-6ffe6a80-a11d-11eb-9606-89f3fd1905c6.png">

**Comment by rishsingh07** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/36331310/115340388-316fbb00-a1c4-11eb-859e-998fc391e2d9.png)

This is already implemented

**Comment by mariahosfeld** [comment]
Closing the issue as it already is implemented.
